# Generated by Django 2.1.15 on 2022-04-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220415_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['id']},
        ),
    ]
