# Generated by Django 2.1.15 on 2022-04-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220415_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={},
        ),
    ]
