# Generated by Django 2.1.15 on 2022-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220415_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
