# Generated by Django 2.1.15 on 2022-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220415_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, default='migration', max_length=255),
            preserve_default=False,
        ),
    ]
