# Generated by Django 2.1.15 on 2022-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220415_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('OUT', 'Outstanding'), ('PAID', 'Paid'), ('VOID', 'Void')], max_length=4),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('ACT', 'Active'), ('CANC', 'Cancelled')], max_length=4),
        ),
    ]
