# Generated by Django 2.1.15 on 2022-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220415_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
