# Generated by Django 2.1.15 on 2022-04-18 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220418_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('ACT', 'Active'), ('CANC', 'Cancelled')], default='ACT', max_length=4),
        ),
    ]
